---
title: "SOK-1303 Mikroøkonomi"
subtitle: "Seminar 1 - Introduksjon"
date: last-modified
date-format: "DD-MM-YYYY"
echo: false
warning: false
format: 
  revealjs:
    auto-stretch: false
    theme: moon
---

## Introduksjon

- Seminarledere: 
  - Daniel Groth, seminarleder gruppe 1 og 2
  - Daniel Johannessen, seminarleder gruppe 3 og 4

## Praktisk informasjon

- Pensum
    - Pensum for seminaret er de samme som for forelesningen
    - To bøker: 
        - "mikroøkonomi - en abc på 1-2-3" av Kjetil Bjorvatn (2. utgave)
        - "mikroøkonomi - Oppgaver, tips og løsningsforslag" av Kjetil Bjorvatn (2. utgave)
- Python som verktøy
- Canvas

## Github

- Seminaroppgaver og materiell legges ut på Github
- Her ligger også seminar notebooks
- Reposetoriet ligger på:
- [https://github.com/uit-sok-1303-v26/uit-sok-1303.v26.github.io](https://github.com/uit-sok-1303-v26/uit-sok-1303.v26.github.io)
- Dere finner det på canvas også

## Filstruktur

- Ha god filstruktur
- Lag en egen mappe for dette kurset
- Lag mapper i mappen for seminar, forelesningsnotater etc.
- Gjør dette konsekvent gjennom studiet

## Arbeidskrav

- Blir en mappeoppgave
- Skrives som en rapport, omtrent 20 sider
- Dokumentet må kodes
- Leveres som en jupyternotatblokk
- Kode skal kunne kjøres, ha korrekt utregning
- Forståelse av hva man har funnet

## Kurssiden og timeplan

- Vi har laget en egen kursside for SOK-1303 Mikroøkonomi:
- [https://uit-sok-1303-v26.github.io/uit-sok-1303.v26.github.io/intro.html](https://uit-sok-1303-v26.github.io/uit-sok-1303.v26.github.io/intro.html)
- Den finner dere også på canvas
- Lenken ligger på hovedsiden til canvas


## Installasjon av python og Visual Studio Code

- Anbefalt å bruke Visual Studio Code (VS Code) som editor
- Installer python fra [python.org](https://www.python.org/downloads/)
- Installer VS Code fra [code.visualstudio.com](https://code.visualstudio.com/download)
- Vi trenger også å installere pip
- Og til slutt pakkene vi trenger

## Litt ekstra informasjon

- Fasit til oppgaver ligger i pensumboken
- Løsningsforslag på kodeoppgaver kommer på neste seminar
- Timeplanen er endret på

## Hjelp til installasjon
